### ISSUE TITLE
Homestead ought to enable host->guest clock synchronization on Hyper-V

### ISSUE THREAD

**Issue by HenkPoley** [laravel/homestead#1300] opened 2019-10-17 06:38 UTC
I currently resolved it with a little bash scripting in after.sh:

```bash
# Hyper-V clock synchronization
if grep -q "hyperv" "/sys/class/ptp/ptp0/clock_name"; then
    sudo apt -y install chrony
    echo "refclock PHC /dev/ptp0 poll 3 dpoll -2 offset 0" | sudo tee -a /etc/chrony/chrony.conf
    sudo service chrony restart
fi
```

Ought to be default, to avoid severe clock drift during standbys. E.g. Which might mean calculated timeouts between your Homestead server and some client on the host are immediate ("in the past"); Certificate errors due to clock synchronization, etc.

**Comment by browner12** [comment] 2019-10-17 13:55
reference #799

**Comment by svpernova09** [comment] 2019-10-17 13:59
I had forgotten about #799.

So this continues to be an issue and NTP didn't fix it?

@HenkPoley anything we do to fix this should be provider agnostic.

**Comment by HenkPoley** [comment] 2019-10-18 07:05
> and NTP didn't fix it?

Are there any hoops I need to jump through to "ntp harder" than the regular Homestead provisioning? My clock often hours off if the host (laptop) was in standby.

The script I sent literally checks if the host-time device is there. It is a problem that exists on Hyper-V. I don't know how you want to make that provider agnostic. _AFAIK_ other virtualization providers just added themselves to the Linux kernel 'regular' time handling, Microsoft didn't. So you have to check, and you do the necessary fix in userland.

**Comment by cbj4074** [comment] 2019-10-18 12:41
I don't have this problem, and I use Hyper-V exclusively, so I wonder what's different between our
 respective environments.

I Hibernate my machine every night, and when I wake it the next day, my VMs all report the correct time. Although, I haven't tested to see if the time is correct *immediately* upon waking, or if there is some lag-time before the correction is made (if a correct is in fact is necessary at all).

Out of curiosity, which version (build number) of Windows 10 are you running @HenkPoley ? And what Configuration Version is displayed in the Hyper-V Manager for the VM in question? `9.0`?

**Comment by svpernova09** [comment] 2019-10-18 14:12
> Are there any hoops I need to jump through to "ntp harder" than the regular Homestead provisioning? My guest clock is often hours off if the host (laptop) was in standby.

No, you as a user shouldn't have to do anything.

I'm quite ok with deferring Hyper-V issues to @cbj4074, if we discover an issue lets get it resolved in the best way we can.

**Comment by cbj4074** [comment] 2019-10-23 12:34
@HenkPoley Any chance you can provide an update here?

Specifically, we'll need the following to investigate further:

1. Windows 10 `version` and `OS build` number that you're running
2. Hyper-V `Configuration Version` that appears next to the VM in Hyper-V Manager
3. Whether you are using `Sleep` or `Hibernate` (or some combination of both) on the host machine

**Comment by cbj4074** [comment] 2019-10-28 12:35
Actually, upon further testing, I can confirm that this clock drift occurs in my Homestead guest VM, too.

In reading through #799 , I don't see that a proper "solution" was ever implemented.

Checking the status of the `ntp` service reveals that it's stopped:

```
vagrant@homestead:~$ sudo systemctl status ntp
● ntp.service - Network Time Service
   Loaded: loaded (/lib/systemd/system/ntp.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:ntpd(8)
```

After starting the service with `sudo systemctl start ntp`, the clock was corrected within a few minutes.

But as @browner12 noted in the other Issue, `ntpdate` is deprecated in favor of `timedatectl`  (see: https://help.ubuntu.com/lts/serverguide/NTP.html ):

> ntpdate is considered deprecated in favor of timedatectl (or chrony) and thereby no more installed by default. timesyncd will generally do the right thing keeping your time in sync, and chrony will help with more complex cases.

The article suggests checking the service status:

```
systemctl status systemd-timesyncd
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Fri 2019-10-25 21:12:43 UTC; 2 days ago
     Docs: man:systemd-timesyncd.service(8)
  Process: 760 ExecStart=/lib/systemd/systemd-timesyncd (code=exited, status=0/SUCCESS)
 Main PID: 760 (code=exited, status=0/SUCCESS)
   Status: "Idle."

Oct 21 17:25:59 homestead systemd-timesyncd[760]: Network configuration changed, trying to establish connection.
Oct 21 18:00:09 homestead systemd-timesyncd[760]: Synchronized to time server 91.189.89.198:123 (ntp.ubuntu.com).
Oct 25 21:12:43 homestead systemd[1]: Stopping Network Time Synchronization...
Oct 25 21:12:43 homestead systemd[1]: Stopped Network Time Synchronization.
```

So, it looks as though the service was stopped two days ago, which was probably when I put the host machine into Hibernation.

We'll have to do a bit more research/testing here, but it seems like the required tools are already present, but perhaps not behaving as we'd like.

Ideally, we can avoid the need to do anything provider-specific, too, but if that's the only viable solution, then so be it.

I'm going to experiment a bit and will post an update once I know more.

**Comment by HenkPoley** [comment] 2019-10-28 13:07
On Hyper-V `chrony` is the recommended time sync client, since it can [read Hyper-V's _precision time protocol_ `/dev/ptp0` file](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync#chrony) as a refclock.

> The Network Time Protocol daemon (ntpd) doesn’t support PTP sources, so using chronyd is recommended. 

Even [Ubuntu's NTP guide](https://help.ubuntu.com/lts/serverguide/NTP.html) mentions `chrony`.

Synchronizing through NTP wil take time and requires a working network, while the host time is exposed as a PTP refclock and is immediate without network requirement.

**Comment by cbj4074** [comment] 2019-10-28 14:18
Thanks for the detailed explanation @HenkPoley . All excellent points.

In consideration of the above, is there any reason *not* to fix this by simply by replacing `ntp` with `chrony` in the Settler build?

Even though this issue is specific to Hyper-V, there seems to be no obvious downside to installing `chrony` across-the-board and not just for Hyper-V, specifically.

**Comment by HenkPoley** [comment] 2019-10-28 15:05
It isn't exactly a _drop-in replacement_, as it doesn't seem to read ntpd.conf, but otherwise is appears to be a superset of the required features.

* https://chrony.tuxfamily.org/faq.html#_how_does_code_chrony_code_compare_to_code_ntpd_code
* https://chrony.tuxfamily.org/comparison.html

I'm not sure how `chrony` interacts with the more direct-to-kernel `pmtmr`/`acpi_pm` time setting that VMware uses:
* https://kb.vmware.com/s/article/1006427

**Comment by svpernova09** [comment] 2019-10-30 16:09
> I think for virtual machines on hosts that get suspended,

I think we should expect that *any* host running Homestead could be suspended.

**Comment by HenkPoley** [comment] 2019-10-31 07:38
I see KVM guests can also synchronize their time through `/dev/ptp0`:

https://opensource.com/article/17/6/timekeeping-linux-vms

**Comment by cbj4074** [comment] 2019-11-12 15:13
I've been running `chronyd` for a while now and I concur with @HenkPoley that we definitely need to change the default configuration to reflect

```
makestep 1 -1
```

because the clock on a VM that is hibernated, or example, can never catch-up otherwise (this is explained in the `chronyd` docs).

My feeling is that we should simply replace `ntp` with `chrony` in the Settler build. I don't see any downside to taking that approach.

**Closed** 2019-11-29 18:33 UTC

**Comment by Artoria2e5** [comment] 2024-09-23 00:23
laravel/settler@0677bb7 does not *technically* fix the issue as requested: while it allows chrony to make infinitely many adjustments, the time-sync source is still the internet (specifically, whatever server ubuntu's default chrony config uses) and not the host. There is still quite some value in using the host->guest PTP link, specifically:

* It works almost without latency.
* It lets you poll as frequently as you want without concern to "being a good citizen".
* It... uh, does not rely on anyone else? People won't know how many VMs you have running?

The fix *should* consist of the following, if ptp is really wanted:

```sh
# we could also do some checks using $(systemd-detect-virt),
# but this is simpler.
modprobe ptp_kvm
if [[ -e /dev/ptp_kvm ]]; then
  echo 'ptp_kvm' | sudo tee /etc/modules-load.d/99-ptp_kvm
fi

# now if we have a clock at all, use it as "stratum 2".
# I tightened the poll frequency because we can.
# offset 0 is a no-op, so removed.
# stratum 2 is required to have it work nice when mixed with Internet servers. It's good sense otherwise too.
if [[ -e /dev/ptp0 ]]; then
  # disable all internet sources (optional)
  sed -e 's@^(pool|server)@# \1@g' -i /etc/chrony/chrony.conf
  # add ptp source
  echo "refclock PHC /dev/ptp0 poll 2 dpoll -2 stratum 2" | sudo tee -a /etc/chrony/chrony.conf
fi
```
