### ISSUE TITLE
per project install, make command not working

### ISSUE THREAD

**Issue by frank-bg** [laravel/homestead#1962] opened 2024-03-22 19:43 UTC
## Expected behavior
`php vendor/bin/homestead make` run successfully  

## Actual behavior
throws a fatal error

```
PHP Fatal error:  Declaration of Laravel\Homestead\MakeCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in vendor/laravel/homestead/src/MakeCommand.php on line 68
```

## Steps to reproduce
1. `composer create-project laravel/laravel:^11.0 example-app`
2. `cd example-app`
3. `composer require laravel/homestead --dev`
4. `php vendor/bin/homestead make`

**Comment by acoghlan** [comment] 2024-03-24 00:58
Yes - experiencing the same error.  Runing latest composer, php8.2 on windows 10, trying to get a new laravel 11 site up and running.

**Comment by acoghlan** [comment] 2024-03-24 01:27
Actually, this is a duplicate of #1953

**Comment by frank-bg** [comment] 2024-03-24 15:43
duplicate indeed, didn’t check if there was a previous issue

**Comment by svpernova09** [comment] 2024-04-27 04:02
Tracking in https://github.com/laravel/homestead/issues/1953

**Closed by svpernova09** 2024-04-27 04:02 UTC
