### ISSUE TITLE
Homestead box can't add v13.0.0 in Vagrant (v2.4.0)

### ISSUE THREAD

**Issue by bam515** [laravel/homestead#1908] opened 2023-11-07 05:27 UTC
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.4.0
  - Provider: 7.0.1
  - Homestead: 14.2.2

## Host operating system
Windows 10

## Actual behavior
If I try to add 13.0.0 version of laravel/homestead box using 2.4.0 version of vagrant, it won't add.
![image](https://github.com/laravel/homestead/assets/82380378/b17280d5-6244-48eb-bdb9-74cc9f11f849)

However, if you use version 2.3.4 of vagrant to add the 13.0.0 version of laravel/homestead box, it will be added normally.

**Comment by ducconit** [comment] 2023-11-07 06:57
@bam515  You can follow [this comment](https://github.com/laravel/homestead/issues/1907#issuecomment-1793163768) or downgrade to version 2.3.x.

**Comment by skeeith** [comment] 2023-11-07 07:30
@bam515 this is a duplicate of what I reported https://github.com/laravel/homestead/issues/1907, sadly I think vagrant v2.4.0 is causing bugs on Homestead, even ssh is broken in my machine, currently clean slating everything I could find and retrying to up again my homestead but on vagrant v2.3.7 instead.

here is the temporary solution https://github.com/laravel/homestead/issues/1907#issuecomment-1793163768

**Comment by bam515** [comment] 2023-11-07 12:50
@ducconit Thank you. After executing the command you mentioned, I was able to create a 13.0.0 version of the box.

**Comment by bam515** [comment] 2023-11-07 12:51
@skeeith Thank you. As you said, it looks like there is a bug in version 2.4.0. I'll consider downgrading.

**Comment by ducconit** [comment] 2023-11-08 03:08
@bam515 You can refer to [my comment](https://github.com/laravel/homestead/issues/1907#issuecomment-1800938057). Hope it helps you.

**Comment by bam515** [comment] 2023-11-10 00:09
@ducconit Oh, thank you. Thanks to you, my curiosity was solved. I think I should try it the way you told me.

**Closed** 2023-11-10 05:01 UTC
