### ISSUE TITLE
Revert back to Mariadb 10.1, the latest stable release

### ISSUE THREAD

**Issue by sisve** [laravel/homestead#529] opened 2017-03-27 14:40 UTC
Pull request https://github.com/laravel/homestead/pull/441 (Update Mariadb to 10.2.* to work with Laravel 5.4) introduced Mariadb 10.2 which is not a stable release yet. (It was a beta version when the switch occured,but has since reached a release candidate status.) This change should probably be reverted back to 10.1, the latest stable release of Mariadb.

If this update was done due to the "Specified key was too long; max key length is 767 bytes" users may run into with Laravel 5.4, couldn't we update their my.cnf file instead?

    innodb_file_format=Barracuda
    innodb_large_prefix=1

References:
https://downloads.mariadb.org/mariadb/+releases/
https://github.com/laravel/framework/issues/18201#issuecomment-284131211

**Comment by svpernova09** [comment] 2017-03-27 14:47
@taylorotwell my thought is we should be using stable versions of things. But not sure about having to patch `my.cnf`. Thoughts?

**Comment by andrewhood125** [comment] 2017-03-27 18:13
I actually lean towards dealing with this at the application level. I think it's reasonable to have Homestead be the latest _stable_ version with a relatively standard configuration. 

https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by andrewhood125** [comment] 2017-03-27 18:13
Of course `after.sh` is always an option for folks.

**Comment by sisve** [comment] 2017-03-27 18:45
Consider that people are building applications on homestead running mariadb, but they can then not find a compatible host because they require functionality that in the stable release of mariadb yet. No production environment is running the release candidate.

If we still want to provide support for 10.2, couldn't we extend the mariadb configuration?
`mariadb: [ false | true | stable | 10.1 | 10.2 | 10.3 ]` where true==stable. It would allow people to specifically say "I want Mariadb 10.2", while those that with old files stay on the stable version (which will be 10.2 once it is stable).

Perhaps a bit overkill, but it would allow both types of users, default to stable but allow opt-in to the current release candidate (10.2) or the current development version (10.3).

**Comment by svpernova09** [comment] 2017-03-27 18:50
I'm fine with supporting multiple versions but at the first sign of trouble I'm going to drop support for anything that gives me trouble in the normal Settler -> Homestead -> Release Cycle. I'll always decide to remove (or just not support) something from Homestead (in this case a version of MariaDB) instead of risking shipping the end users something that is broken.

I also don't want to have to keep up with what's stable or not. If there is an official repo that is giving us always stable versions I'd much prefer to use that. Like @andrewhood125 mentioned using different versions of stuff is exactly what `after.sh` was intended. While this use case is a little odd because we don't install maria until we notice the user requiring it. But if the user installs it via `after.sh` the script won't overwrite the install with the specific version from the `install-maria.sh`

**Comment by svpernova09** [comment] 2017-03-28 00:51
Resolved via #531

**Closed by svpernova09** 2017-03-28 00:51 UTC
Labels: Waiting on Release

**Comment by TopFuel** [comment] 2017-07-19 06:52
@svpernova09 Seems like the 10.2 is now released.

**Comment by HSPDev** [comment] 2017-07-19 17:40
I vote to go back to 10.2... It has window functions, why on earth wouldn't we be doing that? :O

**Comment by mmic-bjohnson** [comment] 2017-08-29 21:18
Now that Maria DB 10.2 is stable, it seems prudent to include it in Homestead when `mariadb: true` in `Homestead.yaml`.

Anybody who installs the latest version of Homestead (as of this writing) with `mariadb: true` and Laravel 5.4 is likely to encounter this limitation, which is considerable.

Dealing with this at the application level is not an elegant solution due to the fact that it requires hard-coding a maximum length in a service provider, which will in time become obsolete and require future database migration to reconcile.

Further, the default `ROW_FORMAT`, which is a per-table directive, cannot be set in versions of MariaDB < 10.2.2, which means that there is no elegant solution to this (short of hard-coding the value in the service provider) until MariaDB is upgraded to >= 10.2.2.

For a more detailed explanation, please see: https://github.com/cartalyst/platform/issues/325

**Comment by sisve** [comment] 2017-08-30 06:39
I would like to counter some of your points. I have the urge to correct them whenever I see someone make them, as some kind of information for others finding this issue and reading the comments. This, however, doesn't at all invalidate the idea to upgrade to mariadb 10.2, but that should probably be a separate issue.

> Dealing with this at the application level is not an elegant solution due to the fact that it requires hard-coding a maximum length in a service provider, which will in time become obsolete and require future database migration to reconcile.

> Further, the default ROW_FORMAT, which is a per-table directive, cannot be set in versions of MariaDB < 10.2.2, which means that there is no elegant solution to this (short of hard-coding the value in the service provider) until MariaDB is upgraded to >= 10.2.2.

Using the service provider and a defaultStringLength is really ugly, but lucky only one of the two documented solutions. It just happens that it's the first solution mentioned in the docs, so people stop reading, and start their copy/paste routine. In fact, you can configure your mariadb 10.1 (and older mysql versions) to support these new features; `innodb_file_format=Barracuda` and `innodb_large_prefix=1`. I believe that the proper thing would be to tell developers what they need to configure for things to work. 

You get around the missing innodb_default_row_format variable by setting `'engine' => 'innodb row_format=dynamic'` in your `config/database.php`.

Your linked issue is a 404; I presume it's a private repository.

**Comment by mmic-bjohnson** [comment] 2017-08-30 12:49
Thanks for fleshing-out the details. And indeed you are correct; the linked issue is a private repository. My post makes a lot less sense in light of the fact (it does discuss setting `innodb_file_format=Barracuda` and `innodb_large_prefix=1`). Sorry about that.

> You get around the missing innodb_default_row_format variable by setting 'engine' => 'innodb row_format=dynamic' in your config/database.php.

Good to know. This seems most valuable for new installations.

Also, is there a typo in there? Are those two separate key-value-pairs, or should there be an underscore (not a space) between `innodb` and `row_Format`? Or is `'engine' => 'innodb'` all that's needed and the remainder is a paste-related error?

> I believe that the proper thing would be to tell developers what they need to configure for things to work.

I couldn't agree more. Why none of this information is in the docs is a mystery. I suppose it is in the interest of keeping them terse (at the expense of much frustration, of course).

And yes indeed, none of this makes a case for keeping MariaDB at 10.1 in Homestead. I don't see an existing Issue for upgrading to 10.2, and I'm happy to open one.
