### ISSUE TITLE
the filesystem "vboxsf" is not available

### ISSUE THREAD

**Issue by okneloper** [laravel/homestead#513] opened 2017-03-10 09:48 UTC
Hi,

I am not sure where exactly the issue lies, but after upgrading homestead, vagrant and virtualbox, I am unable to get the VM to work. The output of my `vagrant up` is below. I have noticed that in the 
`homestead-7: /vagrant => D:/Code` line the `D:/Code` bit is whatever folder I am doing `vagrant up` from, no matter what folders I configure in the `Homestead.yaml` file. No solution from SO or github worked for me.

Please can someone advise?

Just to confirm it worked like a charm before.

```
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Clearing any previously set forwarded ports...
==> homestead-7: Clearing any previously set network interfaces...
==> homestead-7: Preparing network interfaces based on configuration...
    homestead-7: Adapter 1: nat
    homestead-7: Adapter 2: hostonly
==> homestead-7: Forwarding ports...
    homestead-7: 80 (guest) => 8000 (host) (adapter 1)
    homestead-7: 443 (guest) => 44300 (host) (adapter 1)
    homestead-7: 3306 (guest) => 33060 (host) (adapter 1)
    homestead-7: 5432 (guest) => 54320 (host) (adapter 1)
    homestead-7: 8025 (guest) => 8025 (host) (adapter 1)
    homestead-7: 27017 (guest) => 27017 (host) (adapter 1)
    homestead-7: 22 (guest) => 2222 (host) (adapter 1)
==> homestead-7: Running 'pre-boot' VM customizations...
==> homestead-7: Booting VM...
==> homestead-7: Waiting for machine to boot. This may take a few minutes...
    homestead-7: SSH address: 127.0.0.1:2222
    homestead-7: SSH username: vagrant
    homestead-7: SSH auth method: private key
==> homestead-7: Machine booted and ready!
[homestead-7] GuestAdditions 5.1.16 running --- OK.
==> homestead-7: Checking for guest additions in VM...
==> homestead-7: Setting hostname...
==> homestead-7: Configuring and enabling network interfaces...
==> homestead-7: Mounting shared folders...
    homestead-7: /vagrant => D:/Code
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

: No such file or directory
```

Windows 8.1 64bit
Version 5.1.16 r113841 (Qt5.6.2)
Vagrant 1.9.2
laravel/homestead (virtualbox, 2.0.0)
Homestead is check out at v5.0.1 (any other version I tried produces the same result)

Vagrantfile is just the default one (`~/Code` directory exists):

```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public

databases:
    - homestead
```

**Comment by andersfloor** [comment] 2017-03-10 10:41
I've got the exact same problem after updating everything (Vagrant, homestead, VirtualBox) to the latest version.
I'm not good at this server-stuff but I believe something is going wrong with the mapping. When I open the shared folders settings in VirtualBox , I see this:

![2017-03-10 11_39_43-2017-03-10 11_29_40-oracle vm virtualbox manager png - photos](https://cloud.githubusercontent.com/assets/16984414/23792221/5363fbba-0586-11e7-8535-86c210ca643e.png)

If I `vagrant ssh` and then run the command `sudo mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant`, I get the "No such file or directory" error. However, if I click the edit button in VirtualBox and select the **vagrant**-path manually, it changes to this:

![2017-03-10 11_37_45-homestead-7 - settings](https://cloud.githubusercontent.com/assets/16984414/23792126/0462dcf2-0586-11e7-9115-97fc528b4728.png)

.. that's a different notation. Now when I run the same mount-command again, it works fine and the Homestead-folder is correctly mapped to /vagrant on the virtual machine. So in my anything-but-expert-view I'd guess something is wrong with the path notation.

**Comment by okneloper** [comment] 2017-03-10 10:56
Just discovered the above in the meantime as well.

Folder path is `\\?\C:\Users\user\Code` in the VBox machine settings.

If I remove the `\\?\` bit and mount the folder manually from command line it works fine. But after reloading the machine the shared folder setting get reset to those erroneous.

**Comment by andersfloor** [comment] 2017-03-10 11:40
Okneloper, I noticed this closed issue from yesterday, it's regarded as a VirtualBox bug and downgrade to 5.2.14 is advised - #510

**Comment by okneloper** [comment] 2017-03-10 12:09
Thanks @andersfloor that's really helpful. Just noticed after reading the other issue that provision process could not be finished and it's not just shared folders that's not working.

Downgrading VirtualBox to 5.1.14 helped.

Can we keep one of these issues open so that people looking for solution can find it more easily?

**Comment by svpernova09** [comment] 2017-03-10 22:27
Duplicate of #510 Nothing we can do unfortunately.

**Closed by svpernova09** 2017-03-10 22:27 UTC
