### ISSUE TITLE
'homestead.app' hangs (Took too long to respond)

### ISSUE THREAD

**Issue by fairbraxton** [laravel/homestead#617] opened 2017-07-24 01:33 UTC
# Edit: This is a known issue with Virtualbox on Linux.
VirtualBox on Linux has a known problem and [has been reported](https://www.virtualbox.org/ticket/16911). To fix this, head over to the [Testbuilds for VirtualBox](https://www.virtualbox.org/wiki/Testbuilds) and update to **5.1.x revision 117130+** and run the .run file it downloads with sudo. 

Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues but will do our best to help. Thank you!

## Versions
  - Vagrant: Run `vagrant -v` to show the version.
Vagrant 1.9.7
  - Provider: Virtualbox, VMWare or Parallels and it's version.
Virtualbox 5.1.24
  - Homestead: Run `homestead --version` to show the version.
Homestead 5.4.0

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.1`. You *will* show as up-to-date from the `~5.0` branch when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Working on Windows, doesn't work on Ubuntu (Dual-boot)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /usb/Dev/Homestead
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Versionr/public

databases:
    - homestead

```

## Vagrant up output
[Output Gist](https://gist.github.com/fairbraxton/70cfbdcf3c7f5a75918f5b2c51c27320)

## Expected behavior
I made a fresh environment (wiped drive) and made Windows-Ubuntu Dual-boot. It all works perfectly fine on the Windows machine, but it doesn't work on Ubuntu.

## Actual behavior
When I go to ```homestead.app``` in Chrome, I get the error: ```homestead.app took too long to respond.```. 

## Steps to reproduce
1. Fresh everything

## References
None.

**Comment by oltreseba** [comment] 2017-07-24 12:59
I'm having a similar problem, it seems like it's unable to connect to the machine using the host only network.

Can you try to reach the ip of the machine? (in your case should be 192.168.10.10) for me it's inaccessible via ssh, ping, http or whatever.

`Vagrant 1.9.1`
`Laravel Homestead 5.4.0`
`Virtualbox 5.1.24 r117012 (Qt5.5.1)`
`Ubuntu 16.04.2 LTS`

`ifconfig` does not return vboxnet0 even though it exists and it's created. `ifconfig -a` returns it.

**Comment by oltreseba** [comment] 2017-07-24 13:26
Found this: https://www.virtualbox.org/ticket/16911
Apparently this is a regression in Virtualbox 5.1.24. I've tried the 5.1.15 (from here: https://www.virtualbox.org/wiki/Testbuilds) and it seems to be working.

**Comment by fairbraxton** [comment] 2017-07-24 16:25
@oltreseba Do you mean 5.1.25? I do not see 5.1.15.

**Comment by oltreseba** [comment] 2017-07-24 17:21
Yes, sorry, the 5.1.25.

**Comment by fairbraxton** [comment] 2017-07-24 17:46
All is working in 5.1.25, let's hope they put out the patch soon. Might as well leave this open until it is out so other users can find it easily?

**Comment by svpernova09** [comment] 2017-07-24 21:18
Going to close this out as it's not a Homestead issue, but labelled it with Vagrant and Virtualbox labels. Thanks for debugging!

**Closed by svpernova09** 2017-07-24 21:18 UTC
Labels: Vagrant Bug, VirtualBox Bug
