### ISSUE TITLE
avahi-daemon.service failed

### ISSUE THREAD

**Issue by scoutman57** [laravel/homestead#1249] opened 2019-07-22 16:59 UTC
Since updating to the latest version avahi-daemon no longer runs.

```bash
    homestead: Running: script: Configure Avahi Service
    homestead: Job for avahi-daemon.service failed because the control process exited with error code.
    homestead: See "systemctl status avahi-daemon.service" and "journalctl -xe" for details.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
 When checking errors
```bash
vagrant@homestead:~$ systemctl status avahi-daemon.service
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-07-22 16:44:35 UTC; 10min ago
  Process: 1233 ExecStart=/usr/sbin/avahi-daemon -s (code=exited, status=255)
 Main PID: 1233 (code=exited, status=255)

Jul 22 16:44:35 homestead systemd[1]: Starting Avahi mDNS/DNS-SD Stack...
Jul 22 16:44:35 homestead avahi-daemon[1233]: Process 1278 died: No such process; trying to remove PID file. (/run/avahi-dae
Jul 22 16:44:35 homestead avahi-daemon[1233]: Missing assignment in /etc/avahi/avahi-daemon.conf:25: <th.vm,armorvox.vm,yata
Jul 22 16:44:35 homestead systemd[1]: avahi-daemon.service: Main process exited, code=exited, status=255/n/a
Jul 22 16:44:35 homestead systemd[1]: avahi-daemon.service: Failed with result 'exit-code'.
Jul 22 16:44:35 homestead systemd[1]: Failed to start Avahi mDNS/DNS-SD Stack.
```

## Steps to reproduce
1. destroy the current box
2. pull the latest version of homestead
3. vagrant up

## References
https://github.com/laravel/homestead/pull/1245

**Comment by scoutman57** [comment] 2019-07-22 17:05
```bash
# This file is part of avahi.
# 
# avahi is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# avahi is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with avahi; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA.

# See avahi-daemon.conf(5) for more information on this configuration
# file!

[server]
#host-name=foo
#domain-name=local
browse-domains=call-length.vm,armorvox.vm,yatango.vm
use-ipv4=yes
use-ipv6=yes
#allow-interfaces=eth0
#deny-interfaces=eth1
#check-response-ttl=no
#use-iff-running=no
#enable-dbus=yes
#disallow-other-stacks=no
#allow-point-to-point=no
#cache-entries-max=4096
#clients-max=4096
#objects-per-client-max=1024
#entries-per-entry-group-max=32
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=yes

[publish]
#disable-publishing=no
#disable-user-service-publishing=no
#add-service-cookie=no
#publish-addresses=yes
publish-hinfo=no
publish-workstation=no
#publish-domain=yes
#publish-dns-servers=192.168.50.1, 192.168.50.2
#publish-resolv-conf-dns-servers=yes
#publish-aaaa-on-ipv4=yes
#publish-a-on-ipv6=no

[reflector]
#enable-reflector=no
#reflect-ipv=no

[rlimits]
#rlimit-as=
#rlimit-core=0
#rlimit-data=8388608
#rlimit-fsize=0
#rlimit-nofile=768
#rlimit-stack=8388608
#rlimit-nproc=3
```

**Comment by scoutman57** [comment] 2019-07-22 17:07
I removed some domain names for privacy, but they all appear to show in avahi-daemon.conf correctly.

**Comment by svpernova09** [comment] 2019-07-22 17:15
@scoutman57 , I'm not able to reproduce:

```
vagrant up                                                                                                                                        
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Importing base box 'laravel/homestead'...
==> homestead: Matching MAC address for NAT networking...
==> homestead: Checking if box 'laravel/homestead' version '8.0.0' is up to date...
==> homestead: Setting the name of the VM: homestead
==> homestead: Clearing any previously set network interfaces...
==> homestead: Preparing network interfaces based on configuration...
    homestead: Adapter 1: nat
    homestead: Adapter 2: hostonly
==> homestead: Forwarding ports...
    homestead: 80 (guest) => 8000 (host) (adapter 1)
    homestead: 443 (guest) => 44300 (host) (adapter 1)
    homestead: 3306 (guest) => 33060 (host) (adapter 1)
    homestead: 4040 (guest) => 4040 (host) (adapter 1)
    homestead: 5432 (guest) => 54320 (host) (adapter 1)
    homestead: 8025 (guest) => 8025 (host) (adapter 1)
    homestead: 9600 (guest) => 9600 (host) (adapter 1)
    homestead: 27017 (guest) => 27017 (host) (adapter 1)
    homestead: 8000 (guest) => 9090 (host) (adapter 1)
    homestead: 22 (guest) => 2222 (host) (adapter 1)
==> homestead: Running 'pre-boot' VM customizations...
==> homestead: Booting VM...
==> homestead: Waiting for machine to boot. This may take a few minutes...
    homestead: SSH address: 127.0.0.1:2222
    homestead: SSH username: vagrant
    homestead: SSH auth method: private key
    homestead: Warning: Connection reset. Retrying...
    homestead: Warning: Remote connection disconnect. Retrying...
    homestead:
    homestead: Vagrant insecure key detected. Vagrant will automatically replace
    homestead: this with a newly generated keypair for better security.
    homestead:
    homestead: Inserting generated public key within guest...
    homestead: Removing insecure key from the guest if it's present...
    homestead: Key inserted! Disconnecting and reconnecting using new SSH key...
==> homestead: Machine booted and ready!
==> homestead: Checking for guest additions in VM...
==> homestead: Setting hostname...
==> homestead: Configuring and enabling network interfaces...
==> homestead: Mounting shared folders...
    homestead: /vagrant => /Users/halo/Code/homestead
    homestead: /home/vagrant/qs => /Users/halo/Code/quickstart-5.7
    homestead: /home/vagrant/dash => /Users/halo/Code/preteckt_dashboard
    homestead: /home/vagrant/fresh => /Users/halo/Code/fresh-laravel
    homestead: /home/vagrant/symfony => /Users/halo/Code/Cours_Symfony4/symfony4
    homestead: /home/vagrant/composer => /Users/halo/Code/composer
==> homestead: Running provisioner: file...
    homestead: /Users/halo/Code/homestead/aliases => /tmp/bash_aliases
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
    homestead:
    homestead: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBeub1sTnpX7Tp7f0ukLAz7dMn7CS9w6eHmc1wtJNp/iXHzyBRKZ+ov8z+voCVJOrSDyTsG0IKcby8+UxwpzR2nyqiBPw+oaSD1elIHFS48h7Wd5f41S6QeHUlhac20fa5EHTnNw9jphtxDuYPa+xiaNdbdvJKC1jZuipsqc4qlcDC1LISOtIsAzMF1fnByWEe3JBvRxvCmegruu424chIGG23elIoBHsOvY/6BI+5G2BNSBvqzHxfQ2mK6j4tEj2K2s+4M3r4FrgZIYgHxxZtADdNGwditFu5ipfaQSc1n5YFQiI87iTO5OZCBdffMY3qQWaE3ne+hAVDSdJLWFDn halo@mobile-rage-work
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
    homestead: Ignoring feature: python because it is set to false
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/rc/k3k9fv1x50n7r10bpcp7xyx00000gn/T/vagrant-shell20190722-68438-jdlhvk.sh
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/rc/k3k9fv1x50n7r10bpcp7xyx00000gn/T/vagrant-shell20190722-68438-knxzqa.sh
==> homestead: Running provisioner: shell...
    homestead: Running: script: Creating Certificate: homestead.test
==> homestead: Running provisioner: shell...
    homestead: Running: script: Creating Site: homestead.test
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/rc/k3k9fv1x50n7r10bpcp7xyx00000gn/T/vagrant-shell20190722-68438-gq0zkz.sh
==> homestead: Running provisioner: shell...
    homestead: Running: script: Checking for old Schedule
==> homestead: Running provisioner: shell...
    homestead: Running: script: Creating Certificate: fresh.test
==> homestead: Running provisioner: shell...
    homestead: Running: script: Creating Site: fresh.test
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/rc/k3k9fv1x50n7r10bpcp7xyx00000gn/T/vagrant-shell20190722-68438-1ixuh2b.sh
==> homestead: Running provisioner: shell...
    homestead: Running: script: Checking for old Schedule
==> homestead: Running provisioner: shell...
    homestead: Running: script: Creating Certificate: symfony.test
==> homestead: Running provisioner: shell...
    homestead: Running: script: Creating Site: symfony.test
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/rc/k3k9fv1x50n7r10bpcp7xyx00000gn/T/vagrant-shell20190722-68438-1cwjut1.sh
==> homestead: Running provisioner: shell...
    homestead: Running: script: Checking for old Schedule
==> homestead: Running provisioner: shell...
    homestead: Running: script: Configure Avahi Service
==> homestead: Running provisioner: shell...
    homestead: Running: script: Clear Variables
==> homestead: Running provisioner: shell...
    homestead: Running: script: Restarting Cron
==> homestead: Running provisioner: shell...
    homestead: Running: script: Restarting Nginx
==> homestead: Running provisioner: shell...
    homestead: Running: script: Creating MySQL Database: homestead
==> homestead: Running provisioner: shell...
    homestead: Running: script: Creating Postgres Database: homestead
==> homestead: Running provisioner: shell...
    homestead: Running: script: Update Composer
    homestead: You are already using composer version 1.8.6 (stable channel).
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/rc/k3k9fv1x50n7r10bpcp7xyx00000gn/T/vagrant-shell20190722-68438-1m9q7f6.sh
==> homestead: Running provisioner: shell...
    homestead: Running: script: Update motd
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/rc/k3k9fv1x50n7r10bpcp7xyx00000gn/T/vagrant-shell20190722-68438-sm9l59.sh
vagrant up: 01:25

vagrant ssh                                                                                                                                            
Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-54-generic x86_64)

Thanks for using
 _                               _                 _
| |                             | |               | |
| |__   ___  _ __ ___   ___  ___| |_ ___  __ _  __| |
| '_ \ / _ \| '_ ` _ \ / _ \/ __| __/ _ \/ _` |/ _` |
| | | | (_) | | | | | |  __/\__ \ ||  __/ (_| | (_| |
|_| |_|\___/|_| |_| |_|\___||___/\__\___|\__,_|\__,_|

* Homestead v9.0.0 released
* Settler v8.0.0 released

0 packages can be updated.
0 updates are security updates.


vagrant@homestead:~$ cat /etc/avahi/avahi-daemon.conf | grep browse
browse-domains=homestead.test,fresh.test,symfony.test
vagrant@homestead:~$

vagrant@homestead:~$ sudo systemctl status avahi-daemon.service
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-07-22 17:11:45 UTC; 2min 23s ago
 Main PID: 4156 (avahi-daemon)
   Status: "avahi-daemon 0.7 starting up."
    Tasks: 2 (limit: 2318)
   CGroup: /system.slice/avahi-daemon.service
           ├─4156 avahi-daemon: running [homestead.local]
           └─4165 avahi-daemon: chroot helper

Jul 22 17:11:45 homestead avahi-daemon[4156]: Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
Jul 22 17:11:45 homestead avahi-daemon[4156]: New relevant interface lo.IPv4 for mDNS.
Jul 22 17:11:45 homestead avahi-daemon[4156]: Network interface enumeration completed.
Jul 22 17:11:45 homestead avahi-daemon[4156]: Registering new address record for fe80::a00:27ff:fea0:f6c4 on eth1.*.
Jul 22 17:11:45 homestead avahi-daemon[4156]: Registering new address record for 192.168.10.10 on eth1.IPv4.
Jul 22 17:11:45 homestead avahi-daemon[4156]: Registering new address record for fe80::a00:27ff:fe89:526e on eth0.*.
Jul 22 17:11:45 homestead avahi-daemon[4156]: Registering new address record for 10.0.2.15 on eth0.IPv4.
Jul 22 17:11:45 homestead avahi-daemon[4156]: Registering new address record for ::1 on lo.*.
Jul 22 17:11:45 homestead avahi-daemon[4156]: Registering new address record for 127.0.0.1 on lo.IPv4.
Jul 22 17:11:46 homestead avahi-daemon[4156]: Server startup complete. Host name is homestead.local. Local service cookie is 513934460.
vagrant@homestead:~$```
 
Can you share with me your full list of domains privately? You can reach me at my first name at firstname + lastname dot me. Or you can PM me on Larachat Slack or Laravel Discord.

**Comment by scoutman57** [comment] 2019-07-22 18:02
I think we have located the issue, but do not currently have a solution. https://github.com/lathiat/avahi/blob/1cc2b8e8d62e939b8bd683f795794878863931af/avahi-daemon/main.c (line 139) has a limit of 16 domains

**Comment by svpernova09** [comment] 2019-07-22 18:57
A potential solution would be to cut off the domain list at 16. So only the first 16 would make it in. 

Any alternative solution that found a better way would be welcome. I'm not currently able to prioritize this very high.

**Comment by mmeyer2k** [comment] 2019-07-23 01:34
@svpernova09 

You can also use /etc/avahi/hosts just like a hosts file. https://linux.die.net/man/5/avahi.hosts

**Comment by scoutman57** [comment] 2019-07-23 01:49
@mmeyer2k  if that's possible, then submit the PR. I am not sure what adding all this stuff to avahi solves. This is out of my realm.

**Comment by svpernova09** [comment] 2019-07-23 02:25
@mmeyer2k go for it!

**Comment by mmeyer2k** [comment] 2019-07-25 19:54
@svpernova09 You can close this issue for now. Seems as though the hosts file does not work the same way as the browse domains.

**Comment by svpernova09** [comment] 2019-07-25 20:34
Thanks for looking into it

**Closed** 2019-07-25 20:33 UTC
