### ISSUE TITLE
Feature Request: Integrate possibility to thave multiple PHP Versions for Apache

### ISSUE THREAD

**Issue by alpham8** [laravel/homestead#892] opened 2018-07-10 11:54 UTC
For now, it is not possible to have mulitple PHP versions with Apache web server. This currently only works with nginx. However, it is possible with Apache, too and therefore it should be integrated easy, since the most dependencies (PHP-FPM) are already installed:
Just add the handlers to apache default configuration (/etc/apache2/sites-enabled/000-default.conf):
```
<IfModule mod_fastcgi.c>
  AddHandler php56-fcgi-www .php
  Action php56-fcgi-www /php56-fcgi-www
  Alias /php56-fcgi-www /usr/lib/cgi-bin/php56-fcgi-www
  FastCgiExternalServer /usr/lib/cgi-bin/php56-fcgi-www -socket /run/php/php5.6-fpm.sock -pass-header Authorization

  <Directory "/usr/lib/cgi-bin">
     Require all granted
  </Directory>
</IfModule>

<IfModule mod_fastcgi.c>
   AddHandler php70-fcgi-www .php
   Action php70-fcgi-www /php70-fcgi-www
   Alias /php70-fcgi-www /usr/lib/cgi-bin/php70-fcgi-www
   FastCgiExternalServer /usr/lib/cgi-bin/php70-fcgi-www -socket /run/php/php7.0-fpm.sock -pass-header Authorization

   <Directory "/usr/lib/cgi-bin">
      Require all granted
   </Directory>
</IfModule>

<IfModule mod_fastcgi.c>
   <FilesMatch ".+\.ph(p[345]?|t|tml)$">
      SetHandler php70-fcgi-www
   </FilesMatch>
</IfModule>
```

And set individual handler for each vhost, e. g. for php-70:
```
SetHandler php70-fcgi-www
```

We need to install fastcgi as well, this can be easily done by:
```
apt-get install libapache2-mod-fastcgi
```

I am not familar with adding things to a vagrant box, nor with ruby. So, please implement that feature.

## Source
https://www.thomaschristlieb.de/mehrere-php-versionen-auf-einem-linux-server-mit-php-fpm/

## Reference Issue
https://github.com/laravel/homestead/issues/630

**Comment by svpernova09** [comment] 2018-07-10 19:59
Duplicate of #890 

Thanks for the example vhosts. I'll see about getting this implemented.

**Closed by svpernova09** 2018-07-10 19:59 UTC
