### ISSUE TITLE
Request for libvirt provider

### ISSUE THREAD

**Issue by paktsardines** [laravel/homestead#1823] opened 2022-12-17 03:24 UTC
Hi guys,

Apologies if this has been asked and dismissed before, but I was wondering how much work it would be to have a libvirt provider in additional to parallels and virtualbox?

I ask because if Linux users want to run a Homestead box, they currently have no alternative but to pollute their beautiful freedom-respecting distributions with Oracle's Virtualbox.  As we all know, Oracle holds the top three positions in Time's Most Hated Software Companies On The Planet.

So, please consider adding a libvirt provider for us Linux users, and help us ward off the return of Lucifer.

**Comment by svpernova09** [comment] 2023-01-05 16:08
This has come up over the years and while I'm not terribly excited about adding another provider; if we can work it into the current Packer-based workflow I'd love to know/see more.

**Comment by csaba215** [comment] 2023-01-07 18:53
The vagrant box can be built using the qemu image after setting up with settler:
packer build -only=qemu packer_templates/ubuntu/ubuntu-20.04-amd64.json

I also made a basic support commit(#1831).

**Comment by svpernova09** [comment] 2023-01-10 03:16
So far so good...

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/967362/211453887-1a214ec3-3031-4489-ae73-43d3c4f6b849.png">

**Comment by svpernova09** [comment] 2023-01-11 00:24
libvirt has been released: https://app.vagrantup.com/laravel/boxes/homestead/versions/13.0.0

**Comment by alexhackney** [comment] 2023-01-11 13:05
@svpernova09 Does this release support virtualbox cause I only see libvirt and parallels in the box options.

I checked out the latest release of homestead and it requires 13 or greater but there is no virtualbox option so am I stuck?

**Comment by mark1282** [comment] 2023-01-12 11:39
I've just noticed this too. Any reason why VirtualBox has been removed as an option?

**Comment by alexhackney** [comment] 2023-01-12 14:32
@mark1282 Yea I tweeted with @svpernova09 and he mentioned that virtualbox has been a pain point for them.

**Comment by svpernova09** [comment] 2023-01-12 14:39
Virtualbox isn't "missing"; I'm unable to build a Virtualbox on either of my macOS machines since I've upgraded to the latest version, Virtualbox no longer functions appropriately and causes [#1815](https://github.com/laravel/homestead/issues/1815)

I've tried building VirtualBox on my Windows 11 machine but have run into several other issues. My next attempt will be to attempt the build on a Rocky Linux system.

I get it, VirtualBox is free and that's why everyone uses it. I'm sorry I can't build a box atm, if it makes you feel any better I can't build `homestead-arm` either because Parallels has also broken something in their SDK again.

libvirt is a hail mary "maybe if this is easy enough", I've not personally tested it but I put it out there for those who are inclined to use libvirt over other providers.

**Comment by svpernova09** [comment] 2023-01-17 00:43
Initial support published. Please open a new issue with info if you're experiencing issues.

**Comment by paktsardines** [comment] 2023-01-18 10:01
Really grateful for the effort that went into this.

Many thanks.

**Comment by svpernova09** [comment] 2023-01-18 14:53
> Really grateful for the effort that went into this. Many thanks.
> […](#)

I had to back out the changes to Homestead https://github.com/laravel/homestead/commit/45f95afaf8e04c4bdb583239721d4b433efe25a6

That block was throwing hard errors even if you didn't use libvirt, other provider blocks work fine like this I'm unsure what the issue is, but could use some debugging.

**Comment by csaba215** [comment] 2023-01-18 15:35
Sorry for the breaking change. I'll submit a revised pull request for it this week.

**Comment by csaba215** [comment] 2023-01-18 18:55
I created a new PR: #1845

**Comment by svpernova09** [comment] 2023-01-27 03:29
#1845 merged and released, please open a new issue if you're having issues. Thanks!

**Closed by svpernova09** 2023-01-27 03:29 UTC
