### ISSUE TITLE
C:\Users\simon>homestead up Bringing machine 'homestead' up with 'virtualbox' provider... ==> homestead: Checking if box 'laravel/homestead' version '9.2.2-alpha1' is up to date... ==> homestead: Running provisioner: file... Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.

### ISSUE THREAD

**Issue by Brumychap** [laravel/homestead#1358] opened 2020-01-26 12:45 UTC
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Run `vagrant -v` to show the version.
  - Provider: Virtualbox, VMWare, Hyper-V, or Parallels and its version.
  - Homestead: You should be on the most recent `release` branch.

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
This is the operating system that you run locally.

## Homestead.yaml
```yaml
# Copy-paste your Homestead.yaml here
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
What should have happened? Please include as much detail as possible.

## Actual behavior
What actually happened? Please include as much detail as possible.

## Steps to reproduce
1.
2.
3.

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by svpernova09** [comment] 2020-01-26 15:42
Open virtual box ui and remove the VM, delete all files option: say yes. From the folder you run vagrant up from run rm .vagrant and then reboot the host machine and vagrant up.

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by svpernova09** [comment] 2020-01-28 02:09
Closing for now, if the above comment hasn't solved the issue please reopen and give us an update.

**Closed** 2020-01-28 02:10 UTC

**Comment by cjsio** [comment] 2022-07-01 03:04
> Open virtual box ui and remove the VM, delete all files option: say yes. From the folder you run vagrant up from run rm .vagrant and then reboot the host machine and vagrant up.
> […](#)
> -- - Joe Ferguson JoeFerguson.me osmihelp.org

Hi Joe, when setting up a fresh Vagrant Homestead on a new Windows 11 machine, I've encountered this same issue.

> $ vagrant up
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Checking if box 'laravel/homestead' version '12.1.0' is up to date...
==> homestead: Running provisioner: file...
Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.

I did not have any issue a few weeks ago when updating 2 Windows 10 machines to the latest Vagrant Homestead, but this Windows 11 machine is giving more difficulty. I have some deviations with the current install that may be related, but I'm unsure.

First up, after installing Vagrant and following Laravel's homestead docs (as done with the Win10 machines), the `vagrant up` command failed with a `certificate revocation check` failure.

> $ vagrant up
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Box 'laravel/homestead' could not be found. Attempting to find and install...
    homestead: Box Provider: virtualbox
    homestead: Box Version: >= 12.0.0, < 13.0.0
The box 'laravel/homestead' could not be found or could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via `vagrant login`. Also, please double-check the name. The expanded URL and error message are shown below:
>
>URL: ["https://vagrantcloud.com/laravel/homestead"]
Error: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

Searching yielded that this is a curl error, and that when using curl via command line that the `--ssl-no-revoke` argument can be passsed to skip revocation checking. I also learned that `curl.exe` comes preloaded with Windows inside the System32 directory, and I made sure that the Win11 box is fully updated as of today (06/30/22) which installed the `2022-06 Cumulative Update for Windows 11 for x64-based Systems (KB5014668)`; however, `vagrant up` still failed with the same error.

To get past the certificate revocation error, I found that the `Vagrantfile` can accept a `config.vm.box_download_insecure = true` setting, so I added that the to `Vagrantfile` which the homestead setup/checkout process created, right inside the `Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|` configblock.

Now homestead setup continued as expected:
> ...
==> homestead: Successfully added box 'laravel/homestead' (v12.1.0) for 'virtualbox'!
...

However, the box did not finish booting up, preventing me from `vagrant ssh`ing into it. I see the following console output:

>homestead: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that Vagrant was unable to communicate with the guest machine within the configured ("config.vm.boot_timeout" value) time period.

And finally, upon calling `vagrant up` again, I receive the error message that led me to discovering this bug report:

>Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.

You stated that deleting and recreating the VM will hopefully correct the issue, though I'm confused as to why this would happen on a completely new install of VirtualBox+Vagrant+Homestead. These are all the steps leading up to the error, so I can now try destroying and recreating the box, but I wanted to get all of this documented in case you're able to reproduce it on Windows 11 or with any of the other provided specifics (like the curl certificate revocation error, which presumably should not be happening at all no matter the host machine's OS).

Thanks for your time.

**Comment by cjsio** [comment] 2022-07-01 03:30
Good news - destroying the vagrant box and calling `vagrant up` again worked as intended. Here's the console output line where the process previously got stuck, and we see some key updating occurring:

>    homestead: SSH auth method: private key
    homestead:
    homestead: Vagrant insecure key detected. Vagrant will automatically replace
    homestead: this with a newly generated keypair for better security.
    homestead:
    homestead: Inserting generated public key within guest...
    homestead: Removing insecure key from the guest if it's present...
    homestead: Key inserted! Disconnecting and reconnecting using new SSH key...
==> homestead: Machine booted and ready!
==> homestead: Checking for guest additions in VM...
==> homestead: Setting hostname...
==> homestead: Configuring and enabling network interfaces...
==> homestead: Mounting shared folders...

This output reminds me that I generated a fresh ssh key using the command that homestead provides when the ssh key is missing at the referenced `homestead.yaml` ssh key location (I don't recall the exact command though). Again, not sure why `vagrant up` would have failed initially on a completely fresh installation, but hopefully this gives enough info to revive this bug report since it can still happen in 2022.
