### ISSUE TITLE
The box you're attempting to add has no available version

### ISSUE THREAD

**Issue by PreranaShrestha** [laravel/homestead#1839] opened 2023-01-14 04:58 UTC
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.3.4
  - Provider: Virtualbox 7.0.4.
  - Homestead: You should be on the most recent `release` branch.

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
mac os

## Homestead.yaml
```yaml
# Copy-paste your Homestead.yaml here
```

---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Box 'laravel/homestead' could not be found. Attempting to find and install...
    homestead: Box Provider: virtualbox
    homestead: Box Version: >= 13.0.0, < 14.0.0
==> homestead: Loading metadata for box 'laravel/homestead'
    homestead: URL: https://vagrantcloud.com/laravel/homestead
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constraints.

Box: laravel/homestead
Address: https://vagrantcloud.com/laravel/homestead
Constraints: >= 13.0.0, < 14.0.0
Available versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.3.0, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 1.0.0, 1.0.1, 1.1.0, 2.0.0, 2.1.0, 2.2.0, 3.0.0, 3.1.0, 4.0.0, 5.0.1, 5.1.0, 5.2.0, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 7.0.0, 7.1.0, 7.2.1, 8.0.0.pre.alpha1, 8.0.0.pre.alpha2, 8.0.0.pre.alpha3, 8.0.0.pre.alpha4, 8.0.0.pre.beta, 8.0.0, 8.0.1, 8.1.0, 8.2.0, 8.2.1, 9.0.0, 9.0.1, 9.1.0, 9.1.1, 9.2.0, 9.3.0, 9.4.0, 9.5.0, 9.5.1, 9.6.0, 9.6.1, 9.7.2, 10.0.0, 10.1.0, 10.1.1, 11.0.0, 11.1.0, 11.3.0, 11.4.0, 11.5.0, 12.0.0, 12.1.0, 12.2.0, 13.0.0

## Expected behavior
What should have happened? Please include as much detail as possible.

## Actual behavior
What actually happened? Please include as much detail as possible.

## Steps to reproduce
1. vagrant up
2.
3.

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by svpernova09** [comment] 2023-01-14 16:15
Duplicate of 

* https://github.com/laravel/homestead/issues/1829
* https://github.com/laravel/homestead/issues/1833
* https://github.com/laravel/homestead/issues/1835

**Closed by svpernova09** 2023-01-14 16:15 UTC

**Comment by svpernova09** [comment] 2023-01-14 18:17
Latest base box has been released for Virtualbox https://app.vagrantup.com/laravel/boxes/homestead/versions/13.0.0
