### ISSUE TITLE
Vagrant up error

### ISSUE THREAD

**Issue by maxyc** [laravel/homestead#886] opened 2018-06-23 11:02 UTC
When I run 'vagrant up' the system installation starts. Installed `mongodb`, and with it in the file `vendor/laravel/homestead/scripts/install-mongo.sh a` set `php`. Then 'vagrant' tries to continue installing applications. But why is it trying to install php again and this falls with the question of how to proceed. then not responding to any actions.

## Versions
  - Vagrant 2.1.1
  - Provider: Virtualbox
  - Homestead: 7.8

## Host operating system
Mint 16

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 1024
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
mariadb: true
backup: true
mongodb: true

keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /var/www/nextrun.gitlab.io
        to: /home/vagrant/code
sites:
    -
        map: nextrun.loc
        to: /home/vagrant/code/public
        schedule: true
        php: '7.2'

databases:
    - homestead

name: nextrun-gitlab-io
hostname: nextrun-gitlab-io
```

**Comment by svpernova09** [comment] 2018-06-23 12:57
Please post a gist of the complete output of vagrant destroy && vagrant up

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by maxyc** [comment] 2018-06-24 11:20
vagrant up #1
https://paste.laravel.io/31230d4f-59e6-4b49-9686-247517972305
#2 https://paste.laravel.io/de8ab724-d819-4bc5-a936-992fbe8f80f9 (here 2 errors, sudo and php)

and destroy (with flag --force all ok too)
vagrant destroy
    nextrun-gitlab-io: Are you sure you want to destroy the 'nextrun-gitlab-io' VM? [y/N] y
==> nextrun-gitlab-io: Destroying VM and associated drives...

**Comment by svpernova09** [comment] 2018-06-24 15:36
I see the errors in the logs thanks. Will try to duplicate this later today.

**Comment by svpernova09** [comment] 2018-06-24 16:18
I can confirm it's caused by `mongodb: true`.  I don't have a fix at the moment. An obvious issue with `install-mongo.sh` is `sudo DEBIAN_FRONTEND=noninteractive` should be `export DEBIAN_FRONTEND=noninteractive` but this doesn't resolve the issue.

Still working on a fix.

**Comment by svpernova09** [comment] 2018-06-24 16:39
Should be resolved via https://github.com/laravel/homestead/releases/tag/v7.9.0

**Closed by svpernova09** 2018-06-24 16:39 UTC
