### ISSUE TITLE
VMWare Workstation Pro 14 Fails at SSH auth method: private key

### ISSUE THREAD

**Issue by keithdoyle9** [laravel/homestead#911] opened 2018-07-24 14:58 UTC
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.1.2
  - Provider: VMWare Workstation Pro 14
  - Homestead: v7.12.0
  - Homestead Vagrant Box: 6.1.0

## Host operating system
Windows 7 - 64-bit

## Homestead.yaml
```yaml
---
ip: "192.168.10.11"
memory: 4096
cpus: 4
provider: vmware_desktop

authorize: C:/Users/kdoyle/.ssh/id_rsa.pub

keys:
    - C:/Users/kdoyle/.ssh/id_rsa

folders:
    - map: C:/Users/kdoyle/code
      to: /home/vagrant/code

sites:
    - map: abc.local
      to: /home/vagrant/code/abc-com
      php: "7.2"
      type: apache
    - map: sub.abc.local
      to: /home/vagrant/code/sub-abc-com
      php: "7.2"
      type: apache

databases:
    - homestead
    - dev_example_com

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
https://gist.github.com/keithdoyle9/202304603bbfd42af276dc6196a13395

## Expected behavior
Machine should've booted up as normal. This worked previously on VMWare Workstation Pro 12.

## Actual behavior
Provisioning sequence timed out at SSH auth method: private key

## Steps to reproduce
1. Install VMWare Workstation Pro 14
2. Install VMWare Vagrant Utility
3. Install Vagrant version 2.1.2
4. Clone Homestead repo and checkout tag v7.12.0
5. Run `init.bat` in Homestead folder
6. Run `vagrant up` in homestead repo

**Comment by svpernova09** [comment] 2018-07-24 15:41
This may require we ship a new box built with a newer version of VMware fusion.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by keithdoyle9** [comment] 2018-07-24 17:44
I'm more than willing to do some testing if that helps.

**Comment by svpernova09** [comment] 2018-07-24 17:59
I’ll have to check the version of fusion I’m on. Will do that when I’m back at the house later this afternoon.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by keithdoyle9** [comment] 2018-07-25 16:07
I added a host IP address to the Default port forwarding and that seems to have resolved the issue. Line 97 in `scripts/homestead.rb`.

```ruby
config.vm.network "forwarded_port", guest: guest, host: host, host_ip: "127.0.0.1", auto_correct: true
```

**Comment by keithdoyle9** [comment] 2018-07-25 17:33
Still unable to access sites set up in Homestead though.

**Comment by keithdoyle9** [comment] 2018-07-25 18:07
Still unable to access sites even with proper host file entries though.

**Comment by svpernova09** [comment] 2018-07-26 15:54
Sorry, I'm out of town without my VMware drive so I can't check, will check when I'm back home / Monday.

**Comment by thecrypticace** [comment] 2018-07-29 16:58
I was having some major VMWare issues with homestead recently on a new Mac (so its definitely not just limited to Windows installs). I ended up having to install VirtualBox as a workaround. I spent several hours trying to fix stuff. I believe the issues are somewhat related to the vagrant vmware utility service. I kept having port conflicts and when I tried to fix them stuff was breaking because of the utility service daemon. Once I got passed all of that I got the machine to provision once but then would be stuck at waiting for SSH whenever I tried to SSH in.

**Comment by svpernova09** [comment] 2018-07-29 18:09
I just got home and unpacked. No promises but I'll see about getting my VMware drive running today.

@thecrypticace what version of VMware?

**Comment by svpernova09** [comment] 2018-07-29 18:43
Update: I'm waiting for the VMware box to download so I can verify current Homestead release works with the current VMware box.

The current VMware box was built on MacOS using VMware Fusion 8.5.10 (7527438).

If I can recreate the issue I'll upgrade to VMware Fusion 10.x (current version) and built the current version of Settler. This should bring VMware box version to the same as the other providers. (VM ware has skipped a few releases)

**Comment by thecrypticace** [comment] 2018-07-29 19:04
Whatever the latest Fusion is. 10.1.2 I think.

**Comment by svpernova09** [comment] 2018-07-29 20:11
I can confirm the current box and the current release of Homestead work on VMware Fusion 8.5.10 (7527438). I'm going to upgrade to the current version and retest.

**Comment by svpernova09** [comment] 2018-07-29 20:42
Looks like I'm not able to reproduce this. I'm about to apply a MacOS update and will retry then to confirm.

Vagrant version: 2.1.2
VMware Fusion 10.1.2 (8502123)
Homestead: `master` branch / latest release

```
vagrant box list
laravel/homestead (vmware_desktop, 6.1.0)
```

`vagrant up`:

```
Bringing machine 'homestead-7' up with 'vmware_fusion' provider...
==> homestead-7: Cloning VMware VM: 'laravel/homestead'. This can take some time...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Verifying vmnet devices are healthy...
==> homestead-7: Preparing network adapters...
==> homestead-7: Fixed port collision for 80 => 8000. Now on port 2200.
==> homestead-7: Fixed port collision for 443 => 44300. Now on port 2201.
==> homestead-7: Fixed port collision for 3306 => 33060. Now on port 2202.
==> homestead-7: Fixed port collision for 4040 => 4040. Now on port 2203.
==> homestead-7: Fixed port collision for 5432 => 54320. Now on port 2204.
==> homestead-7: Fixed port collision for 8025 => 8025. Now on port 2205.
==> homestead-7: Fixed port collision for 27017 => 27017. Now on port 2206.
==> homestead-7: Fixed port collision for 22 => 2222. Now on port 2207.
==> homestead-7: Starting the VMware VM...
==> homestead-7: Waiting for the VM to receive an address...
==> homestead-7: Forwarding ports...
    homestead-7: -- 80 => 2200
    homestead-7: -- 443 => 2201
    homestead-7: -- 3306 => 2202
    homestead-7: -- 4040 => 2203
    homestead-7: -- 5432 => 2204
    homestead-7: -- 8025 => 2205
    homestead-7: -- 27017 => 2206
    homestead-7: -- 22 => 2207
==> homestead-7: Waiting for machine to boot. This may take a few minutes...
    homestead-7: SSH address: 127.0.0.1:2207
    homestead-7: SSH username: vagrant
    homestead-7: SSH auth method: private key
    homestead-7:
    homestead-7: Vagrant insecure key detected. Vagrant will automatically replace
    homestead-7: this with a newly generated keypair for better security.
    homestead-7:
    homestead-7: Inserting generated public key within guest...
    homestead-7: Removing insecure key from the guest if it's present...
    homestead-7: Key inserted! Disconnecting and reconnecting using new SSH key...
==> homestead-7: Machine booted and ready!
==> homestead-7: Setting hostname...
==> homestead-7: Configuring network adapters within the VM...
==> homestead-7: Waiting for HGFS to become available...
==> homestead-7: Enabling and configuring shared folders...
    homestead-7: -- /Users/halo/PhpStormProjects/homestead: /vagrant
    homestead-7: -- /Users/halo/PhpStormProjects/quickstart-5.4: /home/vagrant/qs
==> homestead-7: Running provisioner: file...
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
    homestead-7:
    homestead-7: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBeub1sTnpX7Tp7f0ukLAz7dMn7CS9w6eHmc1wtJNp/iXHzyBRKZ+ov8z+voCVJOrSDyTsG0IKcby8+UxwpzR2nyqiBPw+oaSD1elIHFS48h7Wd5f41S6QeHUlhac20fa5EHTnNw9jphtxDuYPa+xiaNdbdvJKC1jZuipsqc4qlcDC1LISOtIsAzMF1fnByWEe3JBvRxvCmegruu424chIGG23elIoBHsOvY/6BI+5G2BNSBvqzHxfQ2mK6j4tEj2K2s+4M3r4FrgZIYgHxxZtADdNGwditFu5ipfaQSc1n5YFQiI87iTO5OZCBdffMY3qQWaE3ne+hAVDSdJLWFDn halo@mobile-rage-work
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: /var/folders/qn/_9grndp96d56xqcxs0sb2rt80000gn/T/vagrant-shell20180729-8295-18obqgf.sh
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Certificate: qs.localhost
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Site: qs.localhost
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Checking for old Schedule
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Clear Variables
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Restarting Cron
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Restarting Nginx
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating MySQL Database: homestead
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Postgres Database: homestead
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Update Composer
    homestead-7: You are running composer as "root", while "/home/vagrant/.composer" is owned by "vagrant"
    homestead-7: You are already using composer version 1.6.5 (stable channel).
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: /var/folders/qn/_9grndp96d56xqcxs0sb2rt80000gn/T/vagrant-shell20180729-8295-3v2a3f.sh
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: /var/folders/qn/_9grndp96d56xqcxs0sb2rt80000gn/T/vagrant-shell20180729-8295-97pxos.sh
vagrant up: 01:09
```

**Comment by thecrypticace** [comment] 2018-07-29 20:44
Interesting. Were you able to halt and re-up the box?

**Comment by svpernova09** [comment] 2018-07-29 20:44
No, I didn't event halt it, I just hit the restart button on the pending update.

**Comment by thecrypticace** [comment] 2018-07-29 20:45
Okay, I got the box to provision once or twice but any further operation wouldn't work on the box for some reason.

**Comment by svpernova09** [comment] 2018-07-29 21:19
That one good run may have been a fluke. After rebooting from the MacOS update I saw lots of complaining about the box overriding a network setting that vagrant immediately overrides. I'm currently building a new VMware base box. My ISP is pretty miserable atm so it may take a while to get this built and released.

**Comment by svpernova09** [comment] 2018-07-29 21:59
Having ton's of issues trying to get a new box built. Not sure if it's fusion, or me. Will give it a shot later

**Comment by svpernova09** [comment] 2018-07-30 12:36
So I spent the entire night yak shaving VMware. I can't get Fusion to take networking settings that allow it to access the internet AND fetch the preseed file it needs from packer. It's not looking good. Next steps are to purge Fusion and reinstall to see if that gets my networking settings working again in Fusion.

**Comment by svpernova09** [comment] 2018-07-31 01:17
Anyone experincing this issue please update to base box version [6.2.0](https://app.vagrantup.com/laravel/boxes/homestead/versions/6.2.0) (It's only available for VMware atm).

This box was built on Fusion 10.x and "is working fine on my machine™".  Please test to see if this fixes the issues encountered.

**Comment by svpernova09** [comment] 2018-08-02 17:44
@jordanramstad has confirmed this is working. Closing the issue, if you're still having problems with the 6.2.0 box please open a new issue. Thanks to everyone for all the debugging.

**Closed by svpernova09** 2018-08-02 17:44 UTC
